### ISSUE TITLE
关于USVT的实现

### ISSUE THREAD

**Issue by HaoerSlayer** [YyzHarry/ME-Net#1]
作者你好，
我注意到USVT原文中进行重建时需要的特征值是根据S := {i:si ≥ (2 + η)pnpˆ}这个集合获得的，而在你提供的训练代码中似乎是用了一个固定的值int(h*svdprob)来保留能量大的部分,请问这两者是一致的吗，还是说代码中的实现其实就是保留了固定数量的特征值利用PCA重建而已呢？

**Comment by YyzHarry** [comment]
Hi,

Thanks for your interest. In the original paper, \eta is defined to be a tunable hyper-parameter. We did not try much on tuning it, and fixed a value for convenience. We note that, it is well-known that this derived theoretical threshold does not work very well in practical settings, and usually needs some tuning according to different tasks.
